### ISSUE TITLE
OpenPLi 7.2 - some bug

### ISSUE THREAD

**Issue by EnoSat** [fairbird/RaedQuickSignal#12]
Qviart LUNIX 4K
![1_0_19_307_C94_3_EBAF3A_0_0_0_20230112164540](https://user-images.githubusercontent.com/4271667/212119002-0555afef-e3bf-4ff1-9063-1b6201356eb0.jpg)

**Comment by fairbird** [comment]
You need to install python3-six if pyhton3 image or python-six if image python2

**Comment by EnoSat** [comment]
root@lunix4k:~# opkg install python-six
No packages installed or removed.
root@lunix4k:~#

**Comment by fairbird** [comment]
Exactly ... Your image feed missing python-six .. Try to build that package or ask who built image .

**Comment by EnoSat** [comment]
root@lunix4k: # opkg update
Downloading http://downloads.openpli.org/feeds/openpli-7-release/3rd-party-armv7ahf-neon/Packages.gz.
Updated source 'openpli-3rd-party-armv7ahf-neon'.
Downloading http://downloads.openpli.org/feeds/openpli-7-release/3rd-party/Packages.gz.
Updated source 'openpli-3rd-party'.
Downloading http://downloads.openpli.org/feeds/openpli-7-release/3rd-party-lunix4k/Packages.gz.
Updated source 'openpli-3rd-party-lunix4k'.
Downloading http://downloads.openpli.org/feeds/openpli-7-release/all/Packages.gz.
Updated source 'openpli-all'.
Downloading http://downloads.openpli.org/feeds/openpli-7-release/armv7ahf-neon/Packages.gz.
Updated source 'openpli-armv7ahf-neon'.
Downloading http://downloads.openpli.org/feeds/openpli-7-release/lunix4k/Packages.gz.
Updated source 'openpli-lunix4k'.
Downloading http://downloads.openpli.org/feeds/openpli-7-release/picons/Packages.gz.
Updated source 'openpli-picons'.
root@lunix4k: #
- https://forums.openpli.org/topic/88406-python-six-needed/ -

**Comment by EnoSat** [comment]
Means "already installed".

**Comment by fairbird** [comment]
That is old version of python-six dose not full support of ensure_str ...
But I will try to do some things about the ..

**Comment by EnoSat** [comment]
ok ;)

**Comment by fairbird** [comment]
New version .. please try
https://github.com/fairbird/RaedQuickSignal/commit/315dcaecd40d19cf511113cf3b819cc53816a62d

**Comment by EnoSat** [comment]
thanks, now again work
![1_0_19_307_C94_3_EBAF3A_0_0_0_20230113111025](https://user-images.githubusercontent.com/4271667/212294609-57324b6f-31b3-4662-9609-f538ad936abb.jpg)
