### ISSUE TITLE
test

### ISSUE THREAD

**Issue by EnoSat** [fairbird/RaedQuickSignal#2]
satdreamgr 10 hd51
hd51 login: root
root@hd51:~# wget -q "--no-check-certificate" https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh -O - | /bin/sh
/bin/sh: line 6: is: command not found

You have Python3 image

# Your image is OE2.0 #

wget: unrecognized option '--content-disposition'
BusyBox v1.33.2 (2022-02-07 21:01:42 UTC) multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header 'HEADER: VALUE'] [-Y on/off]
        [--no-check-certificate] [-P DIR] [-U AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

        --spider        Only check URL existence: $? is 0 if exists
        --no-check-certificate  Don't validate the server's certificate
        -c              Continue retrieval of aborted transfer
        -q              Quiet
        -P DIR          Save to DIR (default .)
        -S              Show server response
        -T SEC          Network read timeout is SEC seconds
        -O FILE         Save to FILE ('-' for stdout)
        -o LOGFILE      Log messages to FILE
        -U STR          Use STR for User-Agent header
        -Y on/off       Use proxy
root@hd51:~#

define 6.4 clap4k
clap4k login: root
Password:
root@clap4k:~# wget -q "--no-check-certificate" https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh -O - | /bin/sh
/bin/sh: line 6: is: command not found

You have Python2 image

# Your image is OE2.0 #

--2022-06-29 13:07:09--  https://github.com/fairbird/RaedQuickSignal/archive/refs/heads/main.tar.gz
Resolving github.com... 140.82.121.3
Connecting to github.com|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/fairbird/RaedQuickSignal/tar.gz/refs/heads/main [following]
--2022-06-29 13:07:09--  https://codeload.github.com/fairbird/RaedQuickSignal/tar.gz/refs/heads/main
Resolving codeload.github.com... 140.82.121.9
Connecting to codeload.github.com|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘RaedQuickSignal-main.tar.gz’

RaedQuickSignal-main.tar.gz                 [                        <=>                                                     ]  21.25M  4.57MB/s    in 4.8s

2022-06-29 13:07:14 (4.39 MB/s) - ‘RaedQuickSignal-main.tar.gz’ saved [22286106]

cp: target '/tmp' is not a directory
root@clap4k:~#

**Comment by fairbird** [comment]
Try to install `wget` first then try again to install plugin. And give after that your feedback
