### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by EnoSat** [fairbird/RaedQuickSignal#33]
Hi,
this problem image or page ?

`
root@osmio4kplus:~# wget https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh -O - | /bin/sh
--1970-01-01 19:24:40--  https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh
Resolving raw.githubusercontent.com... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com|185.199.111.133|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by ‘CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US’:
  Issued certificate not yet valid.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
root@osmio4kplus:~#
`
wget "--no-check-certificate" https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh -O - | /bin/sh
-this work

**Comment by fairbird** [comment]
That issue from ssl and wget on your image.
But now problem I will as `--no-check-certificate` to solve it from my side!
