### ISSUE TITLE
Dreambox 920 merlin image green screen

### ISSUE THREAD

**Issue by drkalkan99** [fairbird/RaedQuickSignal#47]
dreambox 920 merlin image
oe 2.5
green screen

the screen appears with the assignment made for the add-on from the remote control and the teletext button
then when you press the menu button while in the add-on, it becomes a green screen

> action ->  MenuActions menu
Screen <class 'Plugins.Extensions.RaedQuickSignal.plugin.RaedQuickSignal_setup'>((), {}): <type 'exceptions.NameError'>
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 386, in create
    return screen(self, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py", line 893, in __init__
    self.createConfigList()
  File "/usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py", line 911, in createConfigList
    self.set_fontssize = getConfigListEntry(_("%s") % title88, config.plugins.RaedQuickSignal.fontsSize, _("%s") % title89)
NameError: global name 'title88' is not defined
swig director exception (SWIG director method error.)
0xb4028068(sp=0xbeff8528) <__cxa_throw+168>
0x3d7824(sp=0xbeff8540) <SwigDirector_eActionSlot::action_func2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+848>
0xdbf98(sp=0xbeff8588) <eActionMap::unbindKeyDomain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+1164>
0xda744(sp=0xbeff85d8) <eActionMap::keyPressed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)+1480>
0xd1260(sp=0xbeff8660) <keyEvent(eRCKey const&)+276>
0x2a5d74(sp=0xbeff8690) <eRCInput::keyPressed(eRCKey const&)+252>
0x2a776c(sp=0xbeff86b8) <eRCDeviceInputDev::handleCode(long)+160>
0x2a4bc0(sp=0xbeff86d8) <eRCInputEventDriver::keyPressed(int)+120>
0xe0fe0(sp=0xbeff8700) <eSocketNotifier::activate(int)+272>
0xe314c(sp=0xbeff8740) <eMainloop_native::processOneEvent(int)+2760>
0x2dc850(sp=0xbeff9a00) <eMainloopQt::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+156>
0xb516122c(sp=0xbeff9b28) <QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+276>
0xb516a498(sp=0xbeff9b70) <QCoreApplication::exec()+148>
0x2dc790(sp=0xbeff9ba0) <eMainloopQt::runLoop()+24>
0x2e3d7c(sp=0xbeff9ba8) <our_terminate()+4260>
0xb4aa068c(sp=0xbeff9bc0) <PyEval_EvalFrameEx+24024>
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 8610, in __call__
    return ret(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 70, in action
    res = act()
  File "/usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal/plugin.py", line 767, in showsetup
    self.session.openWithCallback(self.setupback,RaedQuickSignal_setup)
  File "/usr/lib/enigma2/python/mytest.py", line 465, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 495, in open
    dlg.isTmp = True
AttributeError: 'NoneType' object has no attribute 'isTmp'
]]>
        </enigma2crashlog>

**Comment by drkalkan99** [comment]
No, I am not changing anything
When I try to go to the menu section of the plugin while on the screen that comes with the teletext button, it gives an error
Also, when I try to enter the raedQuick plugin while on the plugins list, a green screen error occurs directly
Also, this error only occurs when the merlin image is loaded, there is no problem with other images

**Comment by fairbird** [comment]
If no problem with other images (DreamOS) such as Gemini or newnigma2 or dream-elite .. etc
Then the issue from Merlin image not from plugin. try to test another version release time of merlin.
Because as you see no problem with me on my dm920 + last version of merlin image plugin work just fine ..

![1](https://github.com/user-attachments/assets/1de7c2d8-560d-46a4-af87-eb086076593f)

![2](https://github.com/user-attachments/assets/07bf62d4-0bde-4ec4-8471-52321958579a)

![3](https://github.com/user-attachments/assets/9e9931e6-9534-40b9-9264-0979bdd48cde)

![4](https://github.com/user-attachments/assets/b1b62d0b-6831-4353-be6b-8a23fac846b3)

**Comment by drkalkan99** [comment]
I will try what you said and get back to you with information.
thanks

**Comment by drkalkan99** [comment]
Before uploading a new Merlin image to the device, I tested it today by updating the plugin you made for the last time
There was no crash when pressing the menu button while on the screen that comes with the teletext button of the remote control, and I did not have any problems when I entered from the plugins section
Thank you again

**Comment by fairbird** [comment]
If you have problem with teletext button in Merlin then change the button from plugin select another button.
If the issue solved from your side please close the issue !
Thank you

**Comment by drkalkan99** [comment]
In the screen shown in the picture, instead of the lock image on the right of the four boxes below, the image of the emu used appears. Sometimes it disappears and this lock image appears. Can we do something to make the emu image always appear?
![screenshot](https://github.com/user-attachments/assets/08a2d49b-3792-423e-ad22-d857fb0957d4)
